In [46]:
import numpy as np

In [47]:
##creating array

In [48]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [49]:
arr_list1=np.array(list1)
print(arr_list1)

[1 2 3]


In [50]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [51]:
list1=[1,2,3]
list2=[4,5,6]
arr_list1_2=np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [52]:
print(arr_list1_2.ndim)

2


In [53]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list1_3=np.array([[list1,list2,list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [54]:
print(arr_list1_3.ndim)

3


In [55]:
# 2.numpy array attribute

In [56]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [57]:
print("shape:",arr1.shape)
print("size:",arr1.size)
print("ntype:",arr1.dtype)
print("n_dim:",arr1.ndim)

shape: (2, 3)
size: 6
ntype: int64
n_dim: 2


#crate 2 array:1D and 3D and find it's attribute

In [58]:
#3.Array initialisation methods

In [59]:
# Zero array

zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [60]:
# one array

ones_arr=np.ones((2,3))
print(ones_arr)


[[1. 1. 1.]
 [1. 1. 1.]]


In [61]:
#full array:

full_arr=np.full((3,2),8)
print(full_arr)

[[8 8]
 [8 8]
 [8 8]]


In [62]:
#Identity  matrix(3 * 3):There diagonal element is one and other element is zero

id_arr=np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
# Empty array:
print(np.empty(3))

[1. 1. 1.]


In [64]:
# Evenly spaced array
print(np.arange(1,10,1))  # not include 10

[1 2 3 4 5 6 7 8 9]


In [65]:
# specific number of equally (spaced) values between a range
print(np.linspace(1,10,6))   # spilt value into specific range

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [66]:
#Random value generate array:  All values in float 

r_arr=np.random.rand(3,2)
print(r_arr)

[[0.02015612 0.68402715]
 [0.76374626 0.25121048]
 [0.95019044 0.81198864]]


In [67]:
# Random values array in int
rint_arr=np.random.randint(1,8,(3,3))
print(rint_arr)

[[6 6 6]
 [2 5 6]
 [1 6 6]]


In [68]:
#Array indexing and slicing:

In [69]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [70]:
a=np.array([1,2,3,4,5,6])
print(a[0:3])          #first three element

[1 2 3]


In [71]:
print(a[-3:])       #last three element

[4 5 6]


In [72]:
print(a[1:4])      #middle three element

[2 3 4]


In [73]:
print(a[0::2])       # 2 step between number

[1 3 5]


In [74]:
print(a[::])        #It take bidefault 1 step

[1 2 3 4 5 6]


In [75]:
# two dimensional array:

In [76]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [77]:
print(arr2[0])      #slicing in 2D array
print(arr2[1])

[1 2 3]
[4 5 6]


In [78]:
print(arr2[0][1])

2


In [79]:
print(arr2[1][2])

6


In [80]:
print(arr2[1])
print(arr2[1:])      #Dimension vary

[4 5 6]
[[4 5 6]]


In [81]:
print(arr2[:,0])

#  2D:[rows,columns]
# 3D:[layers/height,rows,columns]

[1 4]


In [91]:
arr3=np.array([[1,2,3],         # dimensional array
               [4,5,6],
               [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [84]:
print(arr3[0][2])
print(arr3[2][2])

3
9


In [85]:
print(arr3[:,0])           #1st column value
print(arr3[:,1])          # 2nd coulmn value
print(arr3[:,2])          #2nd column value

[1 4 7]
[2 5 8]
[3 6 9]


In [86]:
print(arr3[::2,0])       #Jump the value after colon(;) all values are  columns and
                         #before colon(;) all values are row
print(arr3[::,1:2])      # all values taken from first row element

[1 7]
[[2]
 [5]
 [8]]


In [87]:
print(arr3[2::,1:2])

[[8]]


In [88]:
print(arr3[1::,1:2])

[[5]
 [8]]


In [89]:
print(arr3[::2,0])

[1 7]


In [100]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [101]:
reshaped=arr1.reshape((5,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [102]:
# reshaped2=arr1.reshape((2,3))
# print(reshaped2)

In [103]:
arr2=np.array([1,2,3,4,5,6])
print(arr2)

[1 2 3 4 5 6]


In [105]:
reshaped=arr2.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [106]:
reshaped=arr2.reshape((2,3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [109]:
print(reshaped.flatten())       # flatten convert high dimensional array to simple array

[1 2 3 4 5 6]


In [111]:
#6. Array stacking and splitting
#Stacking means adding multiple array
#Two types of stacking are:
#1.vertical and 2.Horizontal

In [122]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack(a))      #vstack is used for vertical stack-row wise
print(np.hstack(b))      #hstack is used for horizontal stack-column wise


[[1]
 [2]
 [3]]
[4 5 6]


In [124]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [130]:
split=np.hsplit(c,3)     #horizontal split

for s in split:
    print(s)
# print(np.hsplit(c,3))

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [131]:
vsplit=np.vsplit(c,2)      #vertical split

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [132]:
#7. Mathematical operation on Array:

In [134]:
a=np.array([10,20,50,-40])
print(a)

[ 10  20  50 -40]


In [136]:
print(a+10)   #add
print(a-30)   #subtract
print(a*2)    #multiplication
print(a/10)   #Divison

[ 20  30  60 -30]
[-20 -10  20 -70]
[ 20  40 100 -80]
[ 1.  2.  5. -4.]


In [138]:
b=np.array([1,4,7])
print(b)

[1 4 7]


In [142]:
print(np.square(b))     #They square the number
print(np.sqrt(b))       # They give us square root of given number

[ 1 16 49]
[1.         2.         2.64575131]


In [149]:
print(np.sin(b))
print(np.cos(b))
print(np.tan(b))
# print(np.sec(b))   #There is no such module in numpy

[ 0.84147098 -0.7568025   0.6569866 ]
[ 0.54030231 -0.65364362  0.75390225]
[1.55740772 1.15782128 0.87144798]


In [150]:
#8.Mathematical operation on Multiple array:|

In [152]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [154]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [156]:
print(np.dot(a,b))    #dot product of given arr a and b

32


In [157]:
print(a.T)   #Transpose

[1 2 3]


In [162]:
t=np.array([[1,2,3],
           [4,5,6]])
print(t)
print(t.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [163]:
#9.statical function

In [164]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [165]:
print(np.sum(a))

21


In [168]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [169]:
# 10. Array comparsion

In [176]:
a=np.array([1,5,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [177]:
print(a == b)        #comapre each element
print(np.array_equal(a,b))    #comparing complete array

[False  True False]
False


In [178]:
#11. Broadcasting

In [180]:
a=np.array([1,2,3,4])
b=np.array([5])
print(a+b)     #add on each element

[6 7 8 9]
